name: Sync to Gitee 
on: 
  push: 
    branches: [ main ] 
# 监听 main 分支的 push 事件 
jobs: 
  sync: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout code from Github
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - name: Mirror to Gitee
      env: 
        GITEE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
      run: | 
        git remote add gitee https://gloria-chen:${GITEE_TOKEN}@gitee.com/gloria-chen/repo_test.git
        git push gitee HEAD:refs/heads/main --force 

